### ISSUE TITLE
redirect after login

### ISSUE THREAD

**Issue by vedant11** [RehanShakoor/explorin#1]
After login, the user isn't redirected on any landing page
kindly check

**Comment by RehanShakoor** [comment]
please follow these conditions while creating a new user.
![Screenshot (2228)](https://user-images.githubusercontent.com/72434568/105991791-3ee83e00-60ca-11eb-81fa-664c7c8df5a1.png)

**Comment by vedant11** [comment]
okay.
so make sure you have a dummy user for giving a demo to someone

**Comment by RehanShakoor** [comment]
One user is.
Name : Rehan_Shakoor
Password : rehan1234
