### ISSUE TITLE
like button bug

### ISSUE THREAD

**Issue by vedant11** [RehanShakoor/explorin#2]
![image](https://user-images.githubusercontent.com/47473330/105988127-3a6d5680-60c5-11eb-9607-e1c05814e0ef.png)

**Comment by RehanShakoor** [comment]
can you please explain when you are getting this error

**Comment by RehanShakoor** [comment]
can you please explain when you are getting this error?

**Comment by vedant11** [comment]
> can you please explain when you are getting this error?

while liking a post

**Comment by RehanShakoor** [comment]
Try to like the post by logging with the user ID I have given in the second
email or create a user with the given restrictions .
As I am not facing the problem for like button. Please confirm if it is
working or not by doing as mentioned.
